# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit new beta build for testing"
  lane :beta do
    #sh "flutter build appbundle -v --build-number #{ENV['GITVERSION_BUILDMETADATA']} --build-name #{ENV['GITVERSION_MAJORMINORPATCH']}"
    firebase_app_distribution(
      app: "1:598133513450:android:1fb98dc6ac2878e18e0b93",
      testers: "hirathameem@ymail.com",
      release_notes: "Lots of amazing new features to test out!",
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      #android_artifact_type: "AAB"
      android_artifact_path: '/Users/hirasalim/AndroidStudioProjects/FirstApp/app/android/app/build/outputs/bundle/release/app-release.aab',
    ) 
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
