// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK-XTaeKoSXhoqqPK19nVFwz7hUpU_JHc',
    appId: '1:598133513450:web:7601612c2a94042f8e0b93',
    messagingSenderId: '598133513450',
    projectId: 'my-test-project-394c0',
    authDomain: 'my-test-project-394c0.firebaseapp.com',
    storageBucket: 'my-test-project-394c0.appspot.com',
    measurementId: 'G-SM23LRWSLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDamli7URIOJLrVw1ih7ralkQUFRbXL3U8',
    appId: '1:598133513450:android:c99bcb0bc3d022b48e0b93',
    messagingSenderId: '598133513450',
    projectId: 'my-test-project-394c0',
    storageBucket: 'my-test-project-394c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUoDrNP4tUbyEjALbrcKMCEPI3fELNOU',
    appId: '1:598133513450:ios:87ad30be4069a3a68e0b93',
    messagingSenderId: '598133513450',
    projectId: 'my-test-project-394c0',
    storageBucket: 'my-test-project-394c0.appspot.com',
    iosClientId: '598133513450-nrbd1dis6jc8505ktp1kkn3tqtb06m5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupNamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaUoDrNP4tUbyEjALbrcKMCEPI3fELNOU',
    appId: '1:598133513450:ios:87ad30be4069a3a68e0b93',
    messagingSenderId: '598133513450',
    projectId: 'my-test-project-394c0',
    storageBucket: 'my-test-project-394c0.appspot.com',
    iosClientId: '598133513450-nrbd1dis6jc8505ktp1kkn3tqtb06m5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupNamer',
  );
}
