name: Publish to firebase app distribution
on:
  push:
    branches:
      - Workflow1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2

      - uses: subosito/flutter-action@v1.5.3

      - name: Install Dependencies
        run: flutter packages get

      - name: Decode Keystore
        id: write_file
        uses: timheur/base64-to-file@v1
        with:
          fileName: "keystores.jks"
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build
        run: flutter build apk
        env:
          ANDROID_KEYSTORE_PATH: ${{ steps.write_file.outputs.filePath }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      - run: bundle exec fastlane beta
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      
        
